Catch java.lang.NoClassDefFoundError for missing dependencies
On the way to make Postgresql jdbc driver work. It refers to
com.sun.jna.win32.StdCallLibrary, which is not available on a Mac.